### ISSUE TITLE
Proxy location 'reload' Property Read-only Error

### ISSUE THREAD

**Issue by alpgul** [MercuryWorkshop/scramjet#12]
[location.ts](https://github.com/MercuryWorkshop/scramjet/blob/main/src/client/location.ts)
```javascript
function createLocation() {
	const loc = new URL(location.href);
	loc.assign = (url) => location.assign(url);
	loc.reload = () => location.reload();
	loc.replace = (url) => location.replace(url);
	loc.toString = () => loc.href;

	return loc;
}
const locationProxy = new Proxy(window.location, {
	get(target, prop) {
		const loc = createLocation();

		return loc[prop];
	},

	set(obj, prop, value) {
		const loc = createLocation();

		if (prop === "href") {
			location.href = value;
		} else {
			loc[prop] = value;
		}

		return true;
	},
});
``` 
When I run the code above, when I call the `locationProxy.reload()` method, I get an error (`TypeError: 'get' on proxy: property 'reload' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function reload() { [native code] }' but got '() => location.reload()')`).

**Comment by luphoria** [comment]
![i said scram_jet](https://github.com/user-attachments/assets/21dc6069-c629-4900-b937-0c31b6a5a998)
