### ISSUE TITLE
release it rn fr

### ISSUE THREAD

**Issue by play452** [MercuryWorkshop/scramjet#13]
i need to scram my jet

**Comment by rifting** [comment]
I said SCRAM!

**Comment by rifting** [comment]
JET!

**Comment by BomberFish** [comment]
![](https://cdn.discordapp.com/attachments/1047253601413763092/1275539882302771230/caption.gif)

**Comment by play452** [comment]
Hello my name is:
Jet

**Comment by wearrrrr** [comment]
Release date will now be delayed for 700 years because of this github issue.

**Comment by play452** [comment]
oops mb want to do double or nothing
