### ISSUE TITLE
Reduce global use

### ISSUE THREAD

**Issue by KTibow** [MercuryWorkshop/scramjet#4]
In modern ES, functions and constants are imported. Scramjet is better than Ultraviolet at doing this, but it still uses globals in a few places:

- `__scramjet$codecs`
This should be exported, and imported everywhere instead. (Also, things should generally be directly imported instead of going through this object instead)
- `__scramjet$config`
This should be exported to users of the module, so that it can be directly modified.
- `__scramjet$bundle`
Why this is called bundle is unclear to me, but regardless, it should be exported and imported everywhere instead. (Also, things should generally be directly imported instead of going through this object instead)
- `ScramjetServiceWorker`
This should be exported to users of the module, so that it can be used.

**Comment by wearrrrr** [comment]
Most of these aren't just exported because they need to be used in the service worker, and service workers for some reason don't support ES style imports, I agree that it would be nice to be able to make detection a bit harder, but globals are probably going to stick around for a while longer

**Comment by Avad3** [comment]
I have it setup this way so that scramjet avoids code-splitting hell. I want scramjet to be as easy as possible to host and it can make it confusing when you have tons of files. Scramjet needs to use parsers on the client and service worker, and if you import these without code-splitting, it bundles with the other files and makes bundles 1mb+ of JS.

__scramjet$bundle is named this way because it bundles all the modules that need to be used on both the client and service worker

**Comment by KTibow** [comment]
I don't have project-specific knowledge of how this works, but in general, an entrypoint should contain everything it needs to work and nothing it doesn't need. If using normal imports causes the size to be too large, I would personally try to figure out how the dependency tree looks and if there are any imports or side effects that should be dropped.

**Comment by KTibow** [comment]
> service workers for some reason don't support ES style imports

does this still happen with
```js
await navigator.serviceWorker.register("sw.js", { type: "module" })
```

**Comment by Scoder12** [comment]
> entrypoint should contain everything it needs to work and nothing it doesn't need

I think what https://github.com/MercuryWorkshop/scramjet/issues/4#issuecomment-2195586912 was trying to say is that if both the client and service worker bundles import what they need, code will be **duplicated** in each bundle rather than **shared** between the bundles.

**Comment by KTibow** [comment]
Usually shared code is automatically chunked out. If the bundler isn't doing that, it might need to be configured.

**Comment by Scoder12** [comment]
like avad3 also said, chunking isn't done in order to make hosting easier (2 files rather than multiple).

**Comment by KTibow** [comment]
In that case, another build step can be added that declares the resources as globals and patches where they are used. If I'm building my own web app, I want my bundler to be able to figure out the optimal way to share common resources.

**Comment by Avad3** [comment]
I have refactored the codebase. The code is actually a lot cleaner now because you can tell where everything is coming from. The only issue I currently have is with my ESBuild config, which I'll eventually fix. For now it's not that important though.
